language: cpp
dist: bionic
sudo: required
git:
  depth: 5

addons:
  apt:
    update: true
    sources:
    # - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libmodplug-dev
      - libavahi-compat-libdnssd-dev
      - libsndfile1-dev
      - libjack-jackd2-dev
      - libfftw3-dev
      - libboost-dev
      - ninja-build

env:
  global:
  - secure: ifC0UBN+k/lpPL3+amsz8lBNpbmDxi/XGRMIXLpRlNq67cSxOK3pF67HSvM1rFtVS5q9pN+MF2Cfq0jEoeqOJht9SiP+gvb1YlKZITNz4XiNgx2oxKnQLxJhc/EH1bd5hkJ9rpgoOAJGGgDGiI/GFsiwb6wrGQ52i3GPNw3QDPMHjDL8lMPCJQ+GP444j+maXQscWsKqLLa0Eeov0hd60T9fYwvDEGzA95X/UcMW9LFEqq9gW1neiv82ga1y7S/pR8ovqasER+wjFBNdfYh9JekRZv7mRjXK45gRWFg3vArEprfbsgQhPNXsXqXP/HbzMV/cpF0Atn+cyd+GxVRn5PdqiJvn73H9612QQQfXc195JcJXFN79ZeoIYxZI9gZt8emHZE1V90AoTthqCDv0lC/qKwH1SpqqrJ07gGh08ZiUTpN5xBerMzWBdhaUpAGRWeC9xO2xDXz3QKmDb8onWpuoQSCfvM8L2uw2UZnB7Hi93wwyb3nb1kw4CW+3HbgdWIOYtNFc8NAnqbk5BHQLZwCYHOAKPZc6Wae1y2sz5Lm/cOHBdN9msA1jTp5A2K/NjBIhOB6k//uTeSZvkwAWeIcxuNG/xxyk1a76sXGN3WNRSiWeR4jAuNt0k6j0QrEI03Vmv7u12MRiwGBI5WDMhvaMHzltCSmSz2tGsfIEfm8=
  - COVERITY_SCAN_NOTIFICATION_EMAIL="serge.poltavski@gmail.com"
  - COVERITY_SCAN_BRANCH_PATTERN="(master|ceammc|devel|coverity-.*)"
  - COVERITY_SCAN_BUILD_COMMAND="make"
  - CTEST_OUTPUT_ON_FAILURE=1
  - CEAMMC_BUILD_DIR="build"

matrix:
  include:
  - compiler: clang
    env: CEAMMC_BUILD_TYPE="Debug" CEAMMC_COVERAGE="OFF"
  - compiler: gcc
    env: CEAMMC_BUILD_TYPE="Debug" CEAMMC_COVERAGE="ON"
  - compiler: gcc
    env: CEAMMC_BUILD_TYPE="Release" CEAMMC_COVERAGE="OFF"

before_install:
- ./ceammc/scripts/travis_before_install.sh

before_script:
- ./ceammc/scripts/travis_configure.sh
- cd ${CEAMMC_BUILD_DIR}

script:
- ninja
- ctest
- ../ceammc/scripts/travis_package.sh

after_success:
- ../ceammc/scripts/travis_coveralls.sh

deploy:
  provider: packagecloud
  repository: pd
  username: ceammc
  token:
      secure: meUzKX3BJut9BqNhGUfK7GNF6xzoNsdpgz40lphytu9ID8vkv2pUQHVkklVifCvJXZMZa8H2ZoyhakRHmhmc9lI2cOuXKx0Nx/yniQYinPzXeYtrmteqWXXCi1coYvM+c02/dY4uDEZHxkmma6zRyNdNx41k0wJVZBvAqEytncwisRZn7TUJfHl7fjlzX7VYCFTP8fOa8dWSXng0t7jj3KLWPbLDQDQYqhcAj0Jh2TnxfG5gxYBorWgPJkHsbkZhW4gwYKZnD8QhovC9IgGhuReHS8oF+rbikfwbp//kxNCZkfarhi0q4YoKdx9OfRsgsDB0fRnh6kUY9J326K6vnSXFOFm7BKLvrnF4rgJGaGfGb+d9M9w5AlDGpJPZJVmF4uK49O0bYsc8/BH4NXTsq/5eDOL3G/lZMj+mD4720QRiCJg/KDecWKkn+LvuJ/7I2nmV88WhMhdA9WeDJzyJl2SMeeuI+fihCrbsNhqA/STy/ZurDhLA9xJ2vx7fBum29VIfxdc48J6jBtPQN3Xn8Cn3mYGE+06LWj0V1kYGWDO9MazecLS94aGZyi2cm/ssmFJioLI1dwnr5ZMhkDTmw29EJ3mInOvuWeUAHyYDHWEy16iUGqmVFKucrUS0aFczOkgWxdg0mxI9EMis1IjdiA8vjTKYEekTAfOdncmKuk4=
  dist: ubuntu/trusty
  skip_cleanup: true
  package_glob: "*.deb"
  on:
    branch: deploy
    condition: ${CEAMMC_BUILD_TYPE} = Release
