os: Visual Studio 2015

version: '{build}'

#clone_depth: 5

cache:
- tcl-latest.zip
- tk-latest.zip

environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
    TCL_URL: "https://github.com/tcltk/tcl/archive/release.zip"
    TCL_ARCHIVE: "tcl-latest.zip"
    TK_URL: "https://github.com/tcltk/tk/archive/release.zip"
    TK_ARCHIVE: "tk-latest.zip"
    TCL_INSTALL_DIR: "C:/Tcl"
    BOOST_ROOT: "C:/Libraries/boost_1_63_0"
    matrix:
    - MINGW_DIR: mingw

install:
    - if not exist "%TCL_ARCHIVE%" appveyor DownloadFile "%TCL_URL%" -FileName "%TCL_ARCHIVE%"
    - if not exist "%TK_ARCHIVE%" appveyor DownloadFile "%TK_URL%" -FileName "%TK_ARCHIVE%"
    - 7z x -y "%TCL_ARCHIVE%" > nul
    - 7z x -y "%TK_ARCHIVE%" > nul
    # install TCL
    - cd tcl-release/win
    - call "%VCVARS%"
    - set INSTALLDIR=%TCL_INSTALL_DIR%
    - nmake -nologo -f makefile.vc all install
    - cd ../..
    # install Tk
    - cd tk-release/win
    - set TCLDIR=../../tcl-release
    - nmake -nologo -f makefile.vc all install
    - cd ../..
    - dir C:\Tcl\bin

before_build:
    - dir
    - git submodule init
    - git submodule update 
    # CMake refuses to generate MinGW Makefiles if sh.exe is in the Path
    - ps: Get-Command sh.exe -All | Remove-Item
    - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=C:\%MINGW_DIR%\bin:%PATH%
    - echo %PATH%
    - cmake --version
    - echo "NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%"
    - if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" -DWITH_PORTAUDIO=OFF -DBOOST_ROOT=%BOOST_ROOT% -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..

build_script:
    - set VERBOSE=1
    - cmake --build . --use-stderr --target all -- 

